language: node_js
node_js:
  - 10

install:
  - nvm install 10.18.0

before_script:
  - yarn build

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn build && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
